### ISSUE TITLE
Failden docker-compose up

### ISSUE THREAD

**Issue by feliman170** [emanuelepaiano/jespresso-lite#2]
Hi

i have this issue

ERROR: Service 'jespresso' failed to build: ADD failed: file not found in build context or excluded by .dockerignore: stat target/jespresso-0.8.1-SNAPSHOT-UNSTABLE.jar: file does not exist

can you give any idea?

**Comment by epaiano** [comment]
Hi, 
are you trying to compile from source? 
Maybe build has been failed and docker cannot find jar file. You need to check maven and jdk setup.

**Comment by gsiscotty** [comment]
Hy

Having the same issue:

Building jespresso
Step 1/5 : FROM adoptopenjdk/openjdk11:latest
 ---> 95aa255e9fee
Step 2/5 : EXPOSE 8080
 ---> Using cache
 ---> f39c702447c8
Step 3/5 : ARG JAR_FILE=target/jespresso-0.8.1-SNAPSHOT-UNSTABLE.jar
 ---> Using cache
 ---> adc19a816c04
Step 4/5 : ADD ${JAR_FILE} app.jar
ERROR: Service 'jespresso' failed to build: ADD failed: file not found in build context or excluded by .dockerignore: stat target/jespresso-0.8.1-SNAPSHOT-UNSTABLE.jar: file does not exist

please advise.


thank you :-)

**Comment by feliman170** [comment]
My bad!

The first thing to build is the JAR with ./mvnw.

Works Fine! tks.
